### ISSUE TITLE
Import Remi rpm repository keys error

### ISSUE THREAD

**Issue by komaromibandi** [juju4/ansible-MISP#10]
Dear juju4,

I use Centos7 and I always get this error. I use two centos 7 instances on vmware. I updated all of the instances with this ansible module and added some usefull stuff. The preview yml file that I pasted here can be wierd so sorry about that.
---
- name: install required programs
  hosts: [ansible_clients]
  remote_user: root
  vars:
    reboot_connect_timeout: 5
    reboot_post_reboot_delay: 15
    reboot_timeout: 600
  become: true

  tasks:
# Upgrade RHEL family OS packages
  - name: Upgrade RHEL Family OS packages
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"
# Reboot after upgrade
  - name: Reboot host
    reboot:
      connect_timeout: "{{ reboot_connect_timeout }}"
      post_reboot_delay: "{{ reboot_post_reboot_delay }}"
      reboot_timeout: "{{ reboot_timeout }}"
#install epel release
  - name: install epel
    yum:
      name: epel-release
      state: latest
# Install everything else
  - name: install git
    yum:
      name: git
      state: latest

  - name: centos | installing open-vm-tools
    yum: name=open-vm-tools state=present
    when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware"
  - name: centos | starting and enabling open-vm-tools
    service: name=vmtoolsd.service state=restarted enabled=yes
    when: ansible_os_family == "RedHat" and ansible_virtualization_type == "VMware"
  - name: install wget
    yum:
      name: wget
      state: latest
  - name: install python3
    yum:
      name: python3
      state: latest
  - name: install nano
    yum:
      name: nano
      state: latest
# Install MISP
- name: misp install
  hosts: [ansible_clients]
  roles:
    - juju4.misp
 
The point is that I always get thios error :
  
![image](https://user-images.githubusercontent.com/78871051/167025525-c855c645-96b4-4c5b-a317-cdc749d23081.png)
I hope you can help me.

**Comment by juju4** [comment]
Please use code formatting for your playbook else issue not very readable.

Above is a certificate error.

You include a system update tasks but can you check more specifically ca-certificates packages?

latest ca-certificates-2021.2.50-72.el7_9.noarch.rpm per https://pkgs.org/search/?q=ca-certificates
https://rpms.remirepo.net/ is using Let's Encrypt CA so you must have it locally and trusted
Potentially related to https://blog.devgenius.io/rhel-centos-7-fix-for-lets-encrypt-change-8af2de587fe4

In my regular github actions, only have centos8
https://github.com/juju4/ansible-MISP/actions/runs/2274030895
centos7 removed in Oct 2021 likely because of python3 issues, misp-modules or other. I can't remember exactly.

You can fix certificate issue but I would still recommend to use a more recent release as python 3.6 or 3.8 is often becoming a requirement.

**Comment by komaromibandi** [comment]
Thank you for your answer, next time I will pay more attention to the code formatting guidelines.
